[General]
# General settings

# > TLS engine
tls-provider = openssl

# > Custom GeoIP database
geoip-maxmind-url = https://raw.githubusercontent.com/JMVoid/ipip2mmdb/release/Country.mmdb

# > IPv6 support (off by default)
ipv6 = false

# > Allow Wifi access (iOS only, if remote access is allowed, change "false" to "true")
allow-wifi-access = false
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153
# > Allow Wifi access (macOS only, if remote access is allowed, change "127.0.0.1" to "0.0.0.0")
http-listen = 127.0.0.1:6152
socks5-listen = 127.0.0.1:6153

# > Compatibility mode (iOS only)
# compatibility-mode = 0
# > Skip proxy
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, passenger.t3go.cn
# > Exclude simple hostnames
exclude-simple-hostnames = true

# > DNS server
dns-server = 1.0.0.1,8.8.8.8,system
# > Read DNS records from /etc/hosts
read-etc-hosts = true

# Advanced settings

# > Log level
loglevel = notify

# > Return an error page when encountering the REJECT strategy
show-error-page-for-reject = true

# > Always Real IP Hosts
always-real-ip = msftconnecttest.com, msftncsi.com, *.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com

[Replica]
hide-apple-request = 0
hide-crash-reporter-request = 1
hide-udp = 0

[Proxy]
🌐Direct = direct
⛔️Reject = reject
🌑Proxy = ss, 1.2.3.4, 443, encrypt-method=aes-128-gcm, password=password

[Proxy Group]

[Rule]
# Advertising and tracking
DOMAIN-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/Reject.txt,⛔️Reject

# Malaysia local domains and services
DOMAIN-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/MyDirect.txt,🌐Direct

# Apple services
DOMAIN-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/Apple.txt,🌐Direct

# Overseas services and AI platforms
RULE-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/Proxy.txt,🌑Proxy
RULE-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/Ai.txt,🌑Proxy

# Chinese domains and streaming services
DOMAIN-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/StreamingCN.txt,🌑Proxy
DOMAIN-SET,https://raw.githubusercontent.com/dmulle12/back-to-china/master/Rules/China.txt,🌑Proxy

# Local Area Network
RULE-SET,LAN,🌐Direct

# GeoIP China
GEOIP,CN,🌑Proxy

FINAL,🌐Direct
